import type { Metadata } from "next";
import "./globals.css";
import {Toaster} from 'sonner'


export const metadata: Metadata = {
  title: "AdamFolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-full">
      <body
        className="font-poppins scroll-smooth h-full background"
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
